name: Build and Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install uglify
      run: sudo npm install uglify-es -g
    - name: build
      run: cat js/* | uglifyjs -o scripts.min.js
    - name: Commit
      run: |
        git add -f scripts.min.js
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "ci: Automated build push" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
